import type { NextPage } from 'next'
import Head from 'next/head'
import Image from 'next/image'
import { useEffect, useState } from 'react'
import styles from '../styles/Home.module.css'

import { atom, useRecoilState } from 'recoil'
import useInfiniteScroll from 'react-infinite-scroll-hook'
import {Toaster, toast} from 'react-hot-toast'

const userState = atom({
  key:'users', 
  default: [] as USERS[]
})

interface USERS {
  login: string
  avatar_url: string
  
}


const Home: NextPage = () => {

  const [users, setUser] = useRecoilState(userState);

  const [loading, setLoading] = useState(false);

  const [since, setSince] = useState(0);
  const [limit, setLimit] = useState(10);

  useEffect(() => {
      toast.success('Fetched 10  more users',{duration:1000})
  },[users])


  const fetchmore = async (since:number) => {
    setSince(since + limit);
    const response = await fetch(`https://api.github.com/users?since=${since}&per_page=${limit}`);
    const json = await response.json();
    setUser((data) => [...data, ...json]);
  }

  const [sentryRef] = useInfiniteScroll({
    loading, 
    hasNextPage: true,
    delayInMs:500,
    onLoadMore: () => {
      setLoading(true);
      fetchmore(since);
      setLoading(false);
    }
  })

  return (
    <div className={styles.container}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
      <Toaster/>

        {users && users.map((item, index) => {
          return (
            <div key={index} className={styles.item}>
              <p>{item && item.login }</p>
              <img src={item.avatar_url} width={100} height={100} alt={item.avatar_url} />
            </div>
          )
        })}
        {
          !loading && 
          <div ref={sentryRef}>
          <h1>Loading...</h1>
        </div>
        }
        
      </main>

      <footer className={styles.footer}>
        <p>Example created by</p>
        <a
          href="https://twitter.com/biomathcode"
          target="_blank"
          rel="noopener noreferrer"
        >
          @biomathcode
          
        </a>
      </footer>
    </div>
  )
}

export default Home
